input("XOR sign detection - n ^ m < 0 means different signs. Press enter")
print(" 4 ^ 2 =", 4 ^ 2 , "same signs positive ")
n = int(input(" Enter a number ( try 5 or 8 ):"))
guess =(input(" will " + str(n) + " ^ -8 be positive or negative?" ))
input(" XOR is negative when signs differ. Press enter")
print(" ", n, "^ -8 = ", n ^ -8 ,"your guess:",guess)
